apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-ad-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-ad-backend
  template:
    metadata:
      labels:
        app: video-ad-backend
    spec:
      containers:
      - name: app
        image: video-ad-backend:latest
        imagePullPolicy: Never # 👈 This is the key fix!
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "videoads"
        - name: REDIS_ADDR
          value: "redis:6379"
